#!/usr/bin/env python3
"""Build a synthetic ``chat.db`` for screenshots and demos.

    venv/bin/python tools/make_demo_db.py ~/selfbubbles-demo/chat.db            # two weeks of chat ending now
    venv/bin/python tools/make_demo_db.py ~/selfbubbles-demo/chat.db --seed 7   # other timing jitter and colours
    venv/bin/python tools/make_demo_db.py ~/selfbubbles-demo/chat.db --now 2026-10-06T18:00:00
                              # pin "now" (same seed, --now, output path and time zone: same rows)
    venv/bin/python tools/make_demo_db.py ~/selfbubbles-demo/chat.db --relay-port 8780 --contacts-port 8781
                              # other ports in the printed recipe (defaults 8770 and 8771)
    venv/bin/python tools/make_demo_db.py --serve-contacts            # the fictional names, for a demo relay

Run it from the relay checkout.  It needs the checkout's ``tests/`` package and
pytest (both are there after ``venv/bin/pip install -r requirements.txt``),
because the schema and the row builders are the tests' own.  Written and run on
macOS 27 with Python 3.14 only; other macOS versions and other systems are
untested.

What is in the database
-----------------------

Everything is fictional.  Six people exist in it only as five ``+1555...``
numbers and one ``example.com`` address.  Their names (Alex Rivera, Sam Okafor,
Priya Natarajan, Jordan Lee, Morgan Chen, Riley Park) are NOT in the file,
because chat.db stores no names; see "Names" below.  The texts and the two
links are invented, and the one photo is a 320x240 colour gradient this script
draws: a placeholder, not a picture.  ``example.com`` is a domain reserved for
documentation; it is used on purpose, so the address looks ordinary in a
screenshot (the note in ``tests/fixtures/builders.py`` allows it beside
``example.invalid``).

The schema is the macOS 27 profile the relay's tests use
(``tests/fixtures/schema_profiles.py``), created through the same
``tests.conftest.create_fixture_db`` call the tests make (WAL journal, same
DDL), and the rows go in through ``tests/fixtures/builders.py``.  The relay
therefore opens the file exactly like it opens a test database: eight chats
mixing iMessage and SMS (two groups, one of them named "Weekend plan", one
one-to-one chat over an e-mail address), about sixty messages over the last
fourteen calendar days (the oldest scene thirteen days back, the newest message
three minutes before "now"), with threaded replies, tapbacks, one edited message, one
PNG attachment on disk and two URL balloons (an Apple News-style link and a
plain web link) whose ``payload_data`` is a keyed archive the library decodes
without any network access.

Where it is written
-------------------

Nothing is read from a real Messages database, ever.  The output path may not
be under ``~/Library``, and an existing output file is replaced only when it is
a database this script made.  The output may not be inside the relay checkout
either: its ``.gitignore`` covers only the usual demo file names (``demo/``,
``*_relay_state.json``, ``*_files/``), not a database beside them, so a
``git add -A`` could still pick one up.

The outputs are local artefacts; do not commit or share them.  Beside
``NAME.db`` the build writes ``NAME_files/IMG_2048.png``, and a relay started
with the printed recipe adds ``NAME_relay_state.json`` (and its ``.bak``) and
SQLite's ``NAME.db-wal`` / ``NAME.db-shm``.  That state file records the push
token of any phone that connects.  The database records where the photo is: as
``~/...`` when the output is under your home directory (the form real chat.db
rows use), as an absolute path otherwise.  So do not move or copy the output
folder; rebuild at the new place instead.

Times are fixed when the file is built.  Stop the demo relay, re-run the build
and start the relay again right before taking screenshots, so the newest thread
reads as minutes old.

Running a demo relay
--------------------

The database is fictional; the relay in front of it is a real relay on a real
Mac that is signed into a real Messages account.  The build prints the three
commands below with the real paths and a freshly generated token.  Use them
as printed, from the relay checkout.

1. The names, in a terminal of its own::

       venv/bin/python tools/make_demo_db.py --serve-contacts 8771

2. The relay, in a second terminal::

       IMSG_CHATDB=/path/to/chat.db \\
       IMSG_STATE=/path/to/chat_relay_state.json \\
       IMSG_PORT=8770 IMSG_TOKEN=<generated by the build> \\
       IMSG_SELF=+15550100000 TEXT_RELAY_LABEL='Demo phone' APPLE_NEWS_PREVIEWS=0 \\
       BB_URL=http://127.0.0.1:8771 BB_PASSWORD=demo \\
       BEEPER_TOKEN= FCM_CREDS= HA_TOKEN= MAPKIT_TOKEN= \\
       SEND_ENGINES= SEND_APPLESCRIPT_FALLBACK=0 IMESSAGE_CLI=0 \\
       FEATURE_FACETIME=0 FEATURE_MAP=0 FEATURE_TRANSLATE=0 FEATURE_VOICE=0 \\
       venv/bin/python relay.py

3. A check from the same Mac; it prints the eight thread titles::

       curl -s -H 'X-Imsg-Token: <the same token>' http://127.0.0.1:8770/threads | ...

Every variable in step 2 is there for a reason.  A ``.env`` beside ``relay.py``
supplies every variable the command line leaves out, and a variable the command
line sets, even to nothing, is not taken from it:

* ``BEEPER_TOKEN=``, ``FCM_CREDS=``, ``HA_TOKEN=``, ``MAPKIT_TOKEN=``: with the
  values of a real install the relay would merge the real Google Messages
  threads into the demo's thread list, bring up push with the real Firebase
  credentials and serve the family map with its locations.
* ``BB_URL`` and ``BB_PASSWORD``: the names server of step 1, in place of a
  real BlueBubbles server.  A real one would load the Mac's whole address book
  into the demo relay (the app's new-message search serves it) and would still
  not know the six fictional people.
* ``TEXT_RELAY_LABEL``: replaces a real phone label in the header and the
  composer warning of the two SMS threads.
* ``IMSG_SELF``: a fictional own number, so a real one is not reported by the
  demo relay's ``/health``.
* ``SEND_ENGINES=`` with ``SEND_APPLESCRIPT_FALLBACK=0``: the send chain is
  then the names server alone, and it refuses every write.  Without these two,
  anything sent through the demo relay is handed to Messages on this Mac (the
  AppleScript engine needs no configuration), which sends it from the real
  account whenever the chat id exists there.
* ``IMESSAGE_CLI=0``: keeps the edit engine out of that chain.  On a Mac that
  has ``imessage-cli`` installed the relay finds it without being told, and
  an edit asked of the demo relay would then set that tool to work on the
  real Messages.app.
* ``FEATURE_*=0``: a BlueBubbles password alone would make the relay advertise
  FaceTime and voice.
* ``IMSG_TOKEN``: the demo relay may be reachable from the network (the
  command line leaves ``IMSG_BIND`` to ``.env``; without that key the relay
  binds every interface), so the demo gets a token nobody else knows; the
  build generates a new one on every run.
* ``IMSG_PORT``: keeps the demo off an installed relay's port (8700 unless
  changed).
* ``IMSG_STATE``: the demo relay's own state file (pins, read marks, cursor,
  push tokens), so the real ``relay_state.json`` beside ``relay.py`` is not
  touched.
* ``APPLE_NEWS_PREVIEWS=0``: the relay does not try to fetch the fictional
  apple.news link.

Before a screenshot, read the doctor table the relay prints at start.  It must
say: BlueBubbles ``password set, server reachable`` (that is the names server),
Beeper ``disabled``, FCM push ``disabled``, Home Assistant ``disabled``, MapKit
``not set``, send engines ``bluebubbles``, features advertised ``(none)``.

The demo is read-only.  It shows the thread list, the messages, replies,
tapbacks, the edited message, the photo and the two link cards.  Sending,
tapbacks, new chats and FaceTime are refused: the names server answers 501,
and when it is not running the relay answers with an error of its own.  Either
way nothing reaches Messages.  Those features need the real setup, a Mac
signed into Messages.

The phone cannot use ``http://<mac>:8770``: the app speaks HTTPS only, to a
certificate Android trusts.  Point an HTTPS route at the demo port for the
session (README, "Exposing the relay to the phone", with 8770 in place of
8700), then in the app open Settings, section Relay, enter that URL and the
demo token, and press Test connection and Save.  Put the route and the app's
own relay settings back afterwards.

The two ports are only defaults.  ``--relay-port N`` and ``--contacts-port N``
print the recipe with other ones, and the build says so when something on this
Mac already listens on either.

Names
-----

chat.db has no names.  The relay resolves a handle to a name only from the
contact list of a BlueBubbles server, so ``--serve-contacts`` stands in for
one.  It listens on 127.0.0.1 only, answers ``GET /api/v1/ping`` and ``GET
/api/v1/contact`` (the six people in :data:`PEOPLE`), answers 404 to any other
read and 501 to any write, and logs nothing.  The relay asks for the list when
it starts, so start the names server first.  Without it the doctor row reads
``server unreachable`` and the relay titles one-to-one chats by number or
address and the untitled group by its members' handles.

The Android app takes thread titles and sender names from the relay.  The
phone's own address book supplies contact photos (matched by number or address,
then by name) and the names in the People tab of a group's info screen; there a
fictional person shows as their number or address.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import random
import secrets
import shlex
import socket
import sqlite3
import struct
import sys
import time
import zlib
from dataclasses import dataclass, field
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import quote, urlsplit

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from imessage_chatdb import LINK_BALLOON, unix_to_apple  # noqa: E402

from tests.conftest import create_fixture_db  # noqa: E402  (the tests' schema path)
from tests.fixtures import builders  # noqa: E402
from tests.fixtures.keyed_archive_writer import build_link_archive, dump_archive  # noqa: E402
from tests.fixtures.typedstream_writer import encode_attributed_body  # noqa: E402

__all__ = [
    "SCHEMA_PROFILE", "SELF_NUMBER", "PEOPLE", "CHATS", "SCRIPT", "SPAN_DAYS",
    "ATTACHMENT_GUID", "ATTACHMENT_NAME", "MARKER_TABLE", "APPLE_NEWS_URL",
    "DEMO_PHONE_LABEL", "DEMO_RELAY_PORT", "DEMO_CONTACTS_PORT", "DEMO_CONTACTS_PASSWORD",
    "DemoInfo", "NotADemoDatabase", "UnsafeOutputPath",
    "check_output_path", "is_demo_database", "make_png", "build_demo_db",
    "port_in_use", "contacts_payload", "make_contacts_server", "serve_contacts",
    "relay_env", "relay_command", "run_instructions", "main",
]

SCHEMA_PROFILE = "macos27"
#: Marker table (not part of chat.db) that says "this file was made by this script".
MARKER_TABLE = "selfbubbles_demo"

#: A fictional "own number on another device", which is what IMSG_SELF means to
#: the relay.  It is not in the database and changes nothing in the demo; the
#: recipe sets it so that a real IMSG_SELF from .env is not used and is not
#: reported by the demo relay's /health.
SELF_NUMBER = "+15550100000"
#: The demo's TEXT_RELAY_LABEL: the relay shows it in the header and the
#: composer warning of the two SMS threads.
DEMO_PHONE_LABEL = "Demo phone"
#: The ports the printed recipe uses unless ``--relay-port`` /
#: ``--contacts-port`` say otherwise.  8700 is the relay's default port (an
#: installed relay keeps it) and 8701 the default port of its MARIAN_URL.
DEMO_RELAY_PORT = 8770
DEMO_CONTACTS_PORT = 8771
#: What the demo relay sends the names server as its BlueBubbles password.  Not
#: a secret: the server ignores it and listens on 127.0.0.1 only.  It only has
#: to be non-empty, which is what makes the relay ask for contacts at all.
DEMO_CONTACTS_PASSWORD = "demo"

# ---------------------------------------------------------------------------
# fictional people and chats
# ---------------------------------------------------------------------------

ALEX = "+15550100001"
SAM = "+15550100002"
PRIYA = "+15550100003"
JORDAN = "+15550100004"
MORGAN = "morgan.chen@example.com"
RILEY = "+15550100006"

#: handle -> (fictional name, handle service).  The names are not written to
#: the database (chat.db has no names); ``--serve-contacts`` serves them to a
#: demo relay, which is the only way they reach a screen.
PEOPLE: dict[str, tuple[str, str]] = {
    ALEX: ("Alex Rivera", "iMessage"),
    SAM: ("Sam Okafor", "iMessage"),
    PRIYA: ("Priya Natarajan", "iMessage"),
    JORDAN: ("Jordan Lee", "SMS"),
    MORGAN: ("Morgan Chen", "iMessage"),
    RILEY: ("Riley Park", "SMS"),
}

ALEX_GUID = f"iMessage;-;{ALEX}"
SAM_GUID = f"iMessage;-;{SAM}"
PRIYA_GUID = f"iMessage;-;{PRIYA}"
JORDAN_GUID = f"SMS;-;{JORDAN}"
MORGAN_GUID = f"iMessage;-;{MORGAN}"
RILEY_GUID = f"SMS;-;{RILEY}"
WEEKEND_GUID = "iMessage;+;chat700100"
MOVERS_GUID = "iMessage;+;chat700200"


@dataclass(frozen=True)
class ChatSpec:
    guid: str
    service: str                      # "iMessage" or "SMS": message.service and chat.service_name
    members: tuple[str, ...]
    display_name: str | None = None   # groups only; the second group has none on purpose

    @property
    def is_group(self) -> bool:
        return ";+;" in self.guid


CHATS: dict[str, ChatSpec] = {c.guid: c for c in (
    ChatSpec(ALEX_GUID, "iMessage", (ALEX,)),
    ChatSpec(SAM_GUID, "iMessage", (SAM,)),
    ChatSpec(PRIYA_GUID, "iMessage", (PRIYA,)),
    ChatSpec(JORDAN_GUID, "SMS", (JORDAN,)),
    ChatSpec(MORGAN_GUID, "iMessage", (MORGAN,)),
    ChatSpec(RILEY_GUID, "SMS", (RILEY,)),
    ChatSpec(WEEKEND_GUID, "iMessage", (ALEX, SAM, PRIYA), display_name="Weekend plan"),
    ChatSpec(MOVERS_GUID, "iMessage", (PRIYA, MORGAN)),            # untitled group
)}

ATTACHMENT_GUID = "DEMO-ATT-0001"
ATTACHMENT_NAME = "IMG_2048.png"
APPLE_NEWS_URL = "https://apple.news/AdemoLinkToAFictionalStory"
TRAIL_URL = "https://www.example.com/trails/ridgeline-loop"


@dataclass(frozen=True)
class Turn:
    """One scripted message.

    ``sender`` is a handle from :data:`PEOPLE` or ``"me"``.  ``kind`` is
    ``"text"`` (default), ``"photo"`` (the one attachment row), ``"apple_news"``
    / ``"link"`` (URL balloons) or ``"tapback"`` (``text`` is the verb index
    0-5: love, like, dislike, laugh, emphasize, question).  ``ref`` names an
    earlier turn's ``label`` for a reply or a tapback target.  ``edited`` bumps
    ``date_edited``.  ``gap`` is the minutes since the previous turn of the same
    scene (jittered by the seed).
    """

    sender: str
    text: str = ""
    kind: str = "text"
    ref: str | None = None
    label: str | None = None
    edited: bool = False
    gap: int = 4


#: A scene with ``hour=None`` ends this many minutes before "now".
ANCHOR_MINUTES_BEFORE_NOW = 3


@dataclass(frozen=True)
class Scene:
    """A burst of conversation in one chat, ``days_ago`` days before "now" at
    ``hour``:``minute`` local time (``days_ago=0`` is today; the wall-clock time
    of that date, so a daylight-saving change in between does not move it).
    A scene that would reach past "now" is moved back.  ``hour=None``
    anchors the scene to "now" instead: its last message lands
    :data:`ANCHOR_MINUTES_BEFORE_NOW` minutes before it, whatever the clock says,
    so the thread list always opens on something fresh."""

    chat_guid: str
    days_ago: int
    hour: int | None
    minute: int | None
    turns: tuple[Turn, ...]


def T(sender: str, text: str = "", **kw) -> Turn:
    return Turn(sender, text, **kw)


#: The whole conversation, oldest scene first.  Every reply / tapback ``ref``
#: points at a label defined earlier in the same scene.
SCRIPT: tuple[Scene, ...] = (
    Scene(ALEX_GUID, 13, 19, 12, (
        T(ALEX, "Did you end up fixing the kitchen tap?"),
        T("me", "Yes, finally. Turned out to be a worn washer, two dollars at the hardware store.", gap=6),
        T(ALEX, "Of course it was. Three weeks of dripping for a two-dollar part."),
        T("me", "Don't start.", gap=1),
    )),
    Scene(MORGAN_GUID, 12, 9, 40, (
        T(MORGAN, "Morning! Did the slides for Thursday reach you? I sent them from my laptop."),
        T("me", "Got them, thanks. The chart on slide 4 still says Q2, should be Q3.", gap=25),
        T(MORGAN, "Good catch, fixing now."),
    )),
    Scene(WEEKEND_GUID, 11, 20, 5, (
        T(ALEX, "So are we actually doing the hike this weekend or is it going to rain again", label="hike"),
        T(SAM, "Forecast says dry Saturday, 60% Sunday"),
        T(PRIYA, "Saturday then. I can drive, I have room for three.", label="drive"),
        T("me", "Saturday works. What time?"),
        T(ALEX, "Early, before the parking fills up. 7:30 at the trailhead?", label="early"),
        T(SAM, "7:30 is not early, it is the middle of the night", ref="early"),
        T("me", "3", kind="tapback", ref="early"),            # laughed at Alex's 7:30
        T(PRIYA, "I'll pick everyone up at 7. Bring water, it is a long loop.", ref="drive"),
        T("me", TRAIL_URL, kind="link", gap=3),
    )),
    Scene(JORDAN_GUID, 10, 12, 15, (
        T(JORDAN, "Hi, this is Jordan from the garage. Your car is ready, the brake pads were the noise."),
        T("me", "Great, thanks. Can I pick it up after 5?", gap=18),
        T(JORDAN, "We close at 6, that works. Total is 240 with the oil change."),
        T("me", "Perfect, see you then."),
    )),
    Scene(SAM_GUID, 9, 21, 30, (
        T(SAM, "Have you seen this? The bike lane thing finally passed", gap=0),
        T(SAM, APPLE_NEWS_URL, kind="apple_news", gap=0, label="news"),
        T("me", "About time. Only took them four years.", gap=12),
        T("me", "1", kind="tapback", ref="news"),             # liked the link
        T(SAM, "Four years and one very long council meeting"),
    )),
    Scene(PRIYA_GUID, 8, 17, 50, (
        T(PRIYA, "Thanks for Saturday, my legs still hate me"),
        T("me", "Same. Worth it though, that view from the ridge.", gap=9),
        T(PRIYA, "Next time we take the short loop and I will not be talked out of it"),
    )),
    Scene(ALEX_GUID, 7, 13, 5, (
        T("me", "Lunch Thursday? New noodle place on Harbor Street opened.", label="lunch"),
        T(ALEX, "Thursday is bad, I have the dentist. Friday?", ref="lunch", gap=40),
        T("me", "Friday works. 12:30?", gap=3),
        T(ALEX, "12:30. If it is bad you are paying."),
        T("me", "Deal.", gap=1),
    )),
    Scene(MOVERS_GUID, 6, 10, 20, (
        T(PRIYA, "Morgan, you still have the folding table from the office party?"),
        T(MORGAN, "It is in my garage. Want it for the move?", gap=15),
        T(PRIYA, "Yes please, the new place has zero furniture"),
        T("me", "I can bring the van Sunday morning if that helps.", gap=7),
    )),
    Scene(RILEY_GUID, 5, 8, 2, (
        T(RILEY, "Hey neighbor, a package for you was left on our porch by mistake. I put it by your door."),
        T("me", "Oh thank you! That is the lamp I have been waiting for.", gap=33),
        T(RILEY, "No problem. Nice lamp."),
    )),
    Scene(ALEX_GUID, 3, 12, 48, (
        T(ALEX, "", kind="photo", label="photo"),
        T(ALEX, "The noodle place. You were right.", gap=1),
        T("me", "Told you. That broth.", ref="photo", gap=2),
        T("me", "0", kind="tapback", ref="photo"),            # loved the photo
        T(ALEX, "Going back next week, you in?"),
        T("me", "Obviously.", gap=1),
    )),
    Scene(MORGAN_GUID, 2, 16, 10, (
        T(MORGAN, "Deck went over well, they want a follow-up in two weeks."),
        T("me", "Nice work. I will block the time tomorrow.", gap=20, edited=True),
    )),
    Scene(SAM_GUID, 1, 18, 35, (
        T("me", "Are you coming Saturday or are you going to bail again"),
        T(SAM, "I did not bail, I had a flat tire", gap=5),
        T("me", "A flat tire on your bike that was indoors"),
        T(SAM, "It is a mystery to everyone"),
    )),
    Scene(WEEKEND_GUID, 0, 8, 15, (
        T(PRIYA, "Same time this Saturday? Short loop this time, I mean it."),
        T(ALEX, "Short loop is fine. 8:00 though, not 7:30.", gap=12),
        T(SAM, "Finally, a reasonable person"),
        T("me", "8:00 at the trailhead. I will bring coffee.", gap=4),
        T(ALEX, "Now we are talking"),
    )),
    Scene(ALEX_GUID, 0, None, None, (                 # anchored: ends 3 minutes before "now"
        T(ALEX, "Running ten minutes late for lunch, order me the spicy one"),
        T("me", "On it.", gap=1),
    )),
)

#: The calendar days the script covers, today included: the oldest scene is
#: ``SPAN_DAYS - 1`` days back.
SPAN_DAYS = max(scene.days_ago for scene in SCRIPT) + 1

TAPBACK_VERBS = ("Loved", "Liked", "Disliked", "Laughed at", "Emphasized", "Questioned")


# ---------------------------------------------------------------------------
# guards
# ---------------------------------------------------------------------------

class UnsafeOutputPath(RuntimeError):
    """The output path is somewhere a real Messages database could live, or
    inside the relay checkout."""


class NotADemoDatabase(RuntimeError):
    """The output path exists and was not made by this script."""


def check_output_path(path: Path) -> Path:
    """``path`` resolved, or :class:`UnsafeOutputPath` when it is under
    ``~/Library`` or inside the relay checkout.

    Purely lexical; nothing is opened or created.
    """
    resolved = Path(path).expanduser().resolve()
    library = (Path.home() / "Library").resolve()
    if resolved == library or resolved.is_relative_to(library):
        raise UnsafeOutputPath(f"refusing to write under ~/Library (where the real chat.db lives): {resolved}")
    if resolved == ROOT or resolved.is_relative_to(ROOT):
        raise UnsafeOutputPath(
            f"refusing to write inside the relay checkout ({ROOT}): its .gitignore does not "
            "cover a demo database, and the state file beside the database records the push token "
            "of any phone that connects. Choose a path outside it, e.g. ~/selfbubbles-demo/chat.db")
    return resolved


def is_demo_database(path: Path) -> bool:
    """True when ``path`` is a SQLite file carrying the :data:`MARKER_TABLE`."""
    try:
        # percent-encoded: a "#", "?" or "%" in the path is not URI syntax
        conn = sqlite3.connect(f"file:{quote(str(path))}?mode=ro", uri=True)
    except sqlite3.Error:
        return False
    try:
        row = conn.execute(
            "SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = ?", (MARKER_TABLE,)
        ).fetchone()
        return row is not None
    except sqlite3.Error:
        return False
    finally:
        conn.close()


def _remove_previous(path: Path) -> None:
    if path.exists():
        if not is_demo_database(path):
            raise NotADemoDatabase(
                f"{path} exists and is not a database made by this script; delete it yourself first")
        path.unlink()
    for suffix in ("-wal", "-shm"):
        side = path.with_name(path.name + suffix)
        if side.exists():
            side.unlink()


# ---------------------------------------------------------------------------
# the PNGs (standard library only)
# ---------------------------------------------------------------------------

def make_png(width: int, height: int, seed: int = 0, *, compress: int = 6) -> bytes:
    """A real 8-bit RGB PNG: a two-tone gradient with a seeded diagonal stripe.

    ``compress=0`` stores the rows uncompressed, which is how the link hero
    image is kept above the library's 3000-byte embedded-image threshold.
    """
    rng = random.Random(seed)
    a = (rng.randrange(60, 200), rng.randrange(60, 200), rng.randrange(120, 255))
    b = (rng.randrange(180, 255), rng.randrange(90, 200), rng.randrange(40, 160))
    stripe = rng.randrange(width // 4, (3 * width) // 4)
    rows = bytearray()
    for y in range(height):
        rows.append(0)                                   # filter type: none
        fy = y / max(1, height - 1)
        for x in range(width):
            fx = x / max(1, width - 1)
            t = (fx + fy) / 2
            px = [int(a[i] + (b[i] - a[i]) * t) for i in range(3)]
            if abs((x - stripe) - (y - height // 2)) < 3:
                px = [255 - c for c in px]
            rows.extend(px)

    def chunk(tag: bytes, data: bytes) -> bytes:
        return (struct.pack(">I", len(data)) + tag + data
                + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF))

    ihdr = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    return (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr)
            + chunk(b"IDAT", zlib.compress(bytes(rows), compress)) + chunk(b"IEND", b""))


# ---------------------------------------------------------------------------
# building
# ---------------------------------------------------------------------------

@dataclass
class DemoInfo:
    """What :func:`build_demo_db` produced."""

    path: Path
    files_dir: Path
    attachment_path: Path
    state_path: Path
    seed: int
    now: float                                  # Unix seconds the newest scene is anchored to
    chat_rowids: dict[str, int] = field(default_factory=dict)
    message_rowids: dict[str, list[int]] = field(default_factory=dict)   # chat guid -> ROWIDs
    message_count: int = 0
    reply_count: int = 0
    tapback_count: int = 0
    attachment_count: int = 0
    link_count: int = 0
    edited_count: int = 0

    @property
    def chat_count(self) -> int:
        return len(self.chat_rowids)


def _parse_now(value: str | None) -> float:
    if value is None:
        return time.time()
    try:
        parsed = dt.datetime.fromisoformat(value)
    except ValueError as e:
        raise SystemExit(f"--now must be an ISO 8601 timestamp, e.g. 2026-10-06T18:00:00: {e}") from None
    if parsed.tzinfo is None:
        parsed = parsed.astimezone()             # naive -> local time
    return parsed.timestamp()


def _stored_path(path: Path) -> str:
    """What goes into ``attachment.filename`` for the file at ``path``:
    ``~/...`` when it is under the home directory (the form real chat.db rows
    use, and the relay expands it), so the database does not carry the account
    name; the absolute path otherwise."""
    try:
        return "~/" + path.relative_to(Path.home().resolve()).as_posix()
    except ValueError:
        return str(path)


def _schedule(now: float, rng: random.Random) -> list[tuple[float, Scene, Turn]]:
    """Every turn with its Unix timestamp, in chronological order.

    Scenes start at their local wall-clock time ``days_ago`` days before ``now``
    (computed on naive local datetimes, so each date gets its own UTC offset);
    inside a scene each turn follows the previous one by its ``gap`` minutes
    plus 0-90 seconds of jitter.  A scene anchored to "now" (``hour=None``) is
    shifted so its last message is :data:`ANCHOR_MINUTES_BEFORE_NOW` minutes
    old; any other scene that would reach past ``now`` is shifted back to end
    ten minutes before it.
    """
    today = dt.datetime.fromtimestamp(now)               # naive local time, on purpose
    out: list[tuple[float, Scene, Turn]] = []
    for scene in SCRIPT:
        if scene.hour is None:
            t = 0.0                                      # placeholder: shifted below
        else:
            day = today - dt.timedelta(days=scene.days_ago)
            t = day.replace(hour=scene.hour, minute=scene.minute or 0, second=rng.randrange(60),
                            microsecond=0).timestamp()
        stamps = [t]
        for turn in scene.turns[1:]:
            t += turn.gap * 60 + rng.randrange(0, 91)
            stamps.append(t)
        if scene.hour is None:
            shift = (now - ANCHOR_MINUTES_BEFORE_NOW * 60) - stamps[-1]
        else:
            shift = min(0.0, (now - 10 * 60) - stamps[-1])
        stamps = [s + shift for s in stamps]
        out.extend(zip(stamps, [scene] * len(stamps), scene.turns))
    out.sort(key=lambda item: item[0])
    return out


def build_demo_db(output: Path, *, seed: int = 1, now: float | None = None) -> DemoInfo:
    """Create ``output`` (any path not under ``~/Library``) and fill it.

    ``output`` may not be inside the relay checkout either, and an existing
    output is replaced only when :func:`is_demo_database` says this script made
    it.  ``now`` is Unix seconds (default: the current time).  The same
    ``seed``, ``now``, output path and local time zone give the same rows: scene
    times are local wall-clock times, and the attachment row stores where the
    PNG is.  Attachment files go to ``<stem>_files/`` beside the database.
    """
    path = check_output_path(Path(output))
    path.parent.mkdir(parents=True, exist_ok=True)
    _remove_previous(path)
    now = time.time() if now is None else float(now)
    rng = random.Random(seed)

    files_dir = path.with_name(path.stem + "_files")
    files_dir.mkdir(exist_ok=True)
    photo = make_png(320, 240, seed)
    attachment_path = files_dir / ATTACHMENT_NAME
    attachment_path.write_bytes(photo)
    hero = make_png(64, 40, seed + 1, compress=0)       # > 3000 bytes: embedded hero image

    info = DemoInfo(path=path, files_dir=files_dir, attachment_path=attachment_path,
                    state_path=path.with_name(path.stem + "_relay_state.json"),
                    seed=seed, now=now)
    fx = create_fixture_db(path, SCHEMA_PROFILE)
    w = fx.writer
    try:
        w.execute(f"CREATE TABLE {MARKER_TABLE} (key TEXT PRIMARY KEY, value TEXT NOT NULL)")
        w.executemany(f"INSERT INTO {MARKER_TABLE} (key, value) VALUES (?, ?)", [
            ("generator", "selfbubbles-relay tools/make_demo_db.py"),
            ("schema_profile", SCHEMA_PROFILE),
            ("seed", str(seed)),
            ("now_unix", repr(now)),
            ("fictional", "every person, number, address, text and image in this file is invented"),
        ])

        handles = {addr: builders.add_handle(w, addr, service=svc) for addr, (_, svc) in PEOPLE.items()}
        for spec in CHATS.values():
            rowid = builders.add_chat(
                w, spec.guid, 43 if spec.is_group else 45,
                identifier=spec.guid.split(";")[-1],
                display_name=spec.display_name, service_name=spec.service,
                handles=[handles[m] for m in spec.members],
            )
            info.chat_rowids[spec.guid] = rowid
            info.message_rowids[spec.guid] = []

        guids_by_label: dict[tuple[str, int], str] = {}
        n = 0
        for stamp, scene, turn in _schedule(now, rng):
            n += 1
            guid = f"DEMO-MSG-{n:04d}"
            spec = CHATS[scene.chat_guid]
            chat_rowid = info.chat_rowids[scene.chat_guid]
            date_ns = unix_to_apple(stamp)
            from_me = turn.sender == "me"
            handle = None if from_me else handles[turn.sender]
            key = (scene.chat_guid, scene.days_ago)
            # Incoming rows were read 45 s later; outgoing iMessages got a read
            # receipt then (SMS has none); outgoing rows were delivered after 2 s.
            read_at = date_ns + 45_000_000_000
            common = dict(date_ns=date_ns, is_from_me=int(from_me), handle=handle,
                          service=spec.service, guid=guid,
                          date_delivered=date_ns + 2_000_000_000 if from_me else 0,
                          date_read=0 if (from_me and spec.service == "SMS") else read_at)
            if turn.kind == "tapback":
                target = guids_by_label[(key, turn.ref)]
                verb_index = int(turn.text)
                rowid = builders.add_message(
                    w, chat_rowid, text=_tapback_text(scene, verb_index, turn.ref),
                    assoc_guid=f"p:0/{target}", assoc_type=2000 + verb_index, **common)
                info.tapback_count += 1
            elif turn.kind == "photo":
                rowid = builders.add_message(w, chat_rowid, text=None, has_att=1, **common)
                builders.add_attachment(
                    w, rowid, ATTACHMENT_GUID, "image/png", ATTACHMENT_NAME,
                    _stored_path(attachment_path),
                    uti="public.png", total_bytes=len(photo), created_date=date_ns)
                info.attachment_count += 1
            elif turn.kind in ("apple_news", "link"):
                if turn.kind == "apple_news":
                    archive = build_link_archive(
                        turn.text, "Council approves protected bike lanes on Harbor Street",
                        "After four years of hearings, the city will build 3.2 miles of separated "
                        "lanes between the harbor and the rail station.",
                        "Harbor Gazette", wrapped=True)
                    archive["$objects"].append(hero)        # the embedded hero image, a real PNG
                else:
                    archive = build_link_archive(
                        turn.text, "Ridgeline Loop Trail", "9.4 mi loop, 2,100 ft elevation gain. "
                        "Parking fills by 8 am on weekends.", "example.com", wrapped=True)
                payload = dump_archive(archive)
                rowid = builders.add_message(
                    w, chat_rowid, text=turn.text, body=encode_attributed_body(turn.text),
                    balloon=LINK_BALLOON, payload=payload, **common)
                info.link_count += 1
            else:
                reply_to = guids_by_label[(key, turn.ref)] if turn.ref else None
                rowid = builders.add_message(
                    w, chat_rowid, text=turn.text, body=encode_attributed_body(turn.text),
                    reply_to=reply_to, reply_to_part="0:0:0" if reply_to else None,
                    date_edited=date_ns + 90_000_000_000 if turn.edited else 0, **common)
                if reply_to:
                    info.reply_count += 1
                if turn.edited:
                    info.edited_count += 1
            if turn.label:
                guids_by_label[(key, turn.label)] = guid
            info.message_rowids[scene.chat_guid].append(rowid)
            info.message_count += 1
        w.execute("PRAGMA wal_checkpoint(TRUNCATE)").fetchall()
    finally:
        w.close()
    return info


def _tapback_text(scene: Scene, verb_index: int, label: str | None) -> str:
    """An approximation of the text Messages stores for a tapback: the verb plus
    the quoted target text, or "an image" for a photo.  The relay does not rely
    on it (its thread previews say "<verb> a message")."""
    for t in scene.turns:
        if t.label == label:
            verb = TAPBACK_VERBS[verb_index]
            return f"{verb} an image" if t.kind == "photo" else f"{verb} \u201c{t.text}\u201d"
    raise KeyError(label)


# ---------------------------------------------------------------------------
# the names server (--serve-contacts)
# ---------------------------------------------------------------------------

def contacts_payload() -> list[dict]:
    """:data:`PEOPLE` as BlueBubbles contact records: the fields the relay's
    ``load_contacts`` reads (``displayName``, ``phoneNumbers`` / ``emails``
    with an ``address`` each)."""
    out = []
    for handle, (name, _service) in PEOPLE.items():
        first, _, last = name.partition(" ")
        record: dict = {"displayName": name, "firstName": first, "lastName": last,
                        "phoneNumbers": [], "emails": []}
        record["emails" if "@" in handle else "phoneNumbers"].append({"address": handle})
        out.append(record)
    return out


class _ContactsHandler(BaseHTTPRequestHandler):
    """Two reads and nothing else.  A 2xx answer to a write would read to the
    relay as "BlueBubbles sent it", so every write is a 501."""

    server_version = "selfbubbles-demo-contacts"
    sys_version = ""

    def _json(self, status: int, body: dict) -> None:
        data = json.dumps(body).encode()
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    def do_GET(self) -> None:  # noqa: N802  (http.server's naming)
        path = urlsplit(self.path).path.rstrip("/")
        if path == "/api/v1/ping":
            self._json(200, {"status": 200, "message": "demo contacts server", "data": "pong"})
        elif path == "/api/v1/contact":
            self._json(200, {"status": 200, "message": "demo contacts server",
                             "data": contacts_payload()})
        else:
            self._json(404, {"status": 404, "message": "demo contacts server: only the ping "
                                                       "and the contact list are served"})

    def _refuse(self) -> None:
        try:                                             # drain the body before answering
            self.rfile.read(int(self.headers.get("Content-Length") or 0))
        except (ValueError, OSError):
            pass
        self._json(501, {"status": 501, "message": "demo contacts server: read-only, "
                                                   "nothing is sent"})

    do_POST = do_PUT = do_PATCH = do_DELETE = _refuse  # noqa: N815

    def log_message(self, format: str, *args) -> None:  # noqa: A002
        """Silent: the default writes the request line, and the relay puts its
        BlueBubbles password in the query string."""


def port_in_use(port: int) -> bool:
    """True when something on this Mac accepts TCP connections on
    ``127.0.0.1:port`` (a listener on every interface answers there too)."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as probe:
        probe.settimeout(0.5)
        return probe.connect_ex(("127.0.0.1", port)) == 0


def make_contacts_server(port: int = DEMO_CONTACTS_PORT) -> ThreadingHTTPServer:
    """The names server bound to ``127.0.0.1:port`` (``0`` picks a free port),
    not yet serving: call ``serve_forever()`` on it."""
    server = ThreadingHTTPServer(("127.0.0.1", port), _ContactsHandler)
    server.daemon_threads = True
    return server


def serve_contacts(port: int = DEMO_CONTACTS_PORT) -> int:
    """Serve the fictional names until interrupted (the ``--serve-contacts`` mode)."""
    # Checked by hand: http.server opens its socket with SO_REUSEADDR, which on
    # macOS lets a 127.0.0.1 bind succeed beside a listener on every interface.
    if port and port_in_use(port):
        print(f"error: something already listens on port {port} on this Mac (a names server you "
              f"left running?). Otherwise choose another port: --serve-contacts N here, and "
              f"build with --contacts-port N so the recipe matches.", file=sys.stderr)
        return 2
    try:
        server = make_contacts_server(port)
    except OSError as e:
        print(f"error: cannot listen on 127.0.0.1:{port}: {e}", file=sys.stderr)
        return 2
    bound = server.server_address[1]
    print(f"Serving {len(PEOPLE)} fictional contacts on http://127.0.0.1:{bound} "
          "(the ping and the contact list only; every write is refused with 501).")
    print("The demo relay asks for them when it starts, so start it after this. Ctrl-C stops.",
          flush=True)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print()
    finally:
        server.server_close()
    return 0


# ---------------------------------------------------------------------------
# the run recipe
# ---------------------------------------------------------------------------

#: The printed command, one tuple per line.  Every key of :func:`relay_env`
#: appears exactly once.
_RECIPE_LAYOUT: tuple[tuple[str, ...], ...] = (
    ("IMSG_CHATDB",),
    ("IMSG_STATE",),
    ("IMSG_PORT", "IMSG_TOKEN"),
    ("IMSG_SELF", "TEXT_RELAY_LABEL", "APPLE_NEWS_PREVIEWS"),
    ("BB_URL", "BB_PASSWORD"),
    ("BEEPER_TOKEN", "FCM_CREDS", "HA_TOKEN", "MAPKIT_TOKEN"),
    ("SEND_ENGINES", "SEND_APPLESCRIPT_FALLBACK", "IMESSAGE_CLI"),
    ("FEATURE_FACETIME", "FEATURE_MAP", "FEATURE_TRANSLATE", "FEATURE_VOICE"),
)


def relay_env(info: DemoInfo, token: str, *, relay_port: int = DEMO_RELAY_PORT,
              contacts_port: int = DEMO_CONTACTS_PORT) -> dict[str, str]:
    """Every variable the recipe sets for the demo relay.

    The empty values are deliberate.  The relay loads a ``.env`` beside
    ``relay.py`` without overriding, so a variable that is set here, even to
    nothing, is not taken from it; see "Running a demo relay" in the module
    docstring for what each one keeps out.
    """
    return {
        "IMSG_CHATDB": str(info.path),
        "IMSG_STATE": str(info.state_path),
        "IMSG_PORT": str(relay_port),
        "IMSG_TOKEN": token,
        "IMSG_SELF": SELF_NUMBER,
        "TEXT_RELAY_LABEL": DEMO_PHONE_LABEL,
        "APPLE_NEWS_PREVIEWS": "0",
        "BB_URL": f"http://127.0.0.1:{contacts_port}",
        "BB_PASSWORD": DEMO_CONTACTS_PASSWORD,
        "BEEPER_TOKEN": "",
        "FCM_CREDS": "",
        "HA_TOKEN": "",
        "MAPKIT_TOKEN": "",
        "SEND_ENGINES": "",
        "SEND_APPLESCRIPT_FALLBACK": "0",
        "IMESSAGE_CLI": "0",
        "FEATURE_FACETIME": "0",
        "FEATURE_MAP": "0",
        "FEATURE_TRANSLATE": "0",
        "FEATURE_VOICE": "0",
    }


def relay_command(env: dict[str, str]) -> list[str]:
    """The shell command that starts the demo relay with ``env``, as lines
    joined by a trailing backslash.  Values are shell-quoted, so a path with a
    space or a ``#`` survives the paste; an empty value prints as ``KEY=``."""
    laid_out = [key for line in _RECIPE_LAYOUT for key in line]
    if sorted(laid_out) != sorted(env):
        raise KeyError(f"recipe layout and environment differ: {sorted(set(laid_out) ^ set(env))}")
    lines = [" ".join(f"{key}={shlex.quote(env[key]) if env[key] else ''}" for key in line) + " \\"
             for line in _RECIPE_LAYOUT]
    return lines + ["venv/bin/python relay.py"]


def _busy_notes(busy_ports: tuple[int, ...], relay_port: int, contacts_port: int) -> list[str]:
    notes = []
    if relay_port in busy_ports:
        notes += [
            f"NOTE: something already listens on port {relay_port} on this Mac. If it is a demo relay",
            "you left running, stop it before step 2. Otherwise build again with --relay-port N",
            "(a free port): depending on how the other program listens, the relay either fails",
            "to start or starts beside it, and step 3 then reaches the other program.",
            "",
        ]
    if contacts_port in busy_ports:
        notes += [
            f"NOTE: something already listens on port {contacts_port} on this Mac. If it is the names server",
            "of step 1, leave it running and skip step 1. Otherwise build again with",
            "--contacts-port N.",
            "",
        ]
    return notes


def run_instructions(info: DemoInfo, token: str | None = None, *,
                     relay_port: int = DEMO_RELAY_PORT,
                     contacts_port: int = DEMO_CONTACTS_PORT,
                     busy_ports: tuple[int, ...] = ()) -> str:
    """What the build prints: what was written and how to run a demo relay on it.

    ``token`` is the demo relay's IMSG_TOKEN; the default is a new random one,
    so no two runs print the same token.  ``busy_ports`` are the recipe's ports
    that :func:`port_in_use` found taken (``main`` checks; this function opens
    nothing).  The text holds absolute paths and that token: do not paste it
    into documentation.
    """
    token = secrets.token_hex(16) if token is None else token
    env = relay_env(info, token, relay_port=relay_port, contacts_port=contacts_port)
    people = ", ".join(name for name, _ in PEOPLE.values())
    lines = [
        f"Wrote {info.path}",
        f"  {info.chat_count} chats, {info.message_count} messages "
        f"({info.reply_count} replies, {info.tapback_count} tapbacks, {info.edited_count} edited, "
        f"{info.attachment_count} attachment, {info.link_count} link cards)",
        f"  over the last {SPAN_DAYS} calendar days, ending "
        f"{dt.datetime.fromtimestamp(info.now):%Y-%m-%d %H:%M}",
        f"  attachment file: {info.attachment_path}",
        "",
        *_busy_notes(tuple(busy_ports), relay_port, contacts_port),
        "The database is fictional. The relay in front of it is a real relay on a real Mac,",
        "so run these three steps as printed, from the relay checkout.",
        "",
        "1. The names, in a terminal of its own. chat.db has none; the relay takes them from a",
        "   BlueBubbles server's contact list, and this stands in for one on 127.0.0.1 with",
        f"   six fictional people ({people}):",
        "",
        f"  venv/bin/python tools/make_demo_db.py --serve-contacts {contacts_port}",
        "",
        "2. The demo relay, in a second terminal:",
        "",
        *(f"  {line}" for line in relay_command(env)),
        "",
        f"3. A check from this Mac. It prints {info.chat_count} thread titles, people by name:",
        "",
        f"  curl -s -H {shlex.quote('X-Imsg-Token: ' + token)} http://127.0.0.1:{relay_port}/threads \\",
        "    | venv/bin/python -c 'import json, sys; "
        "print(*(t[\"chat_name\"] for t in json.load(sys.stdin)[\"threads\"]), sep=\"\\n\")'",
        "",
        "Keep every variable of step 2. A .env beside relay.py supplies whatever the command",
        "line leaves out; a variable set here, even to nothing, is not taken from it.",
        "  - BEEPER_TOKEN, FCM_CREDS, HA_TOKEN and MAPKIT_TOKEN are empty so a real install's",
        "    Google Messages threads, push credentials and family map stay out of the demo.",
        "  - BB_URL and BB_PASSWORD point at the names server. A real BlueBubbles server would",
        "    load this Mac's whole address book into the demo relay.",
        f"  - TEXT_RELAY_LABEL ({DEMO_PHONE_LABEL!r}) replaces a real phone label in the two SMS",
        "    threads; IMSG_SELF is a fictional number so a real one stays out of /health.",
        "  - SEND_ENGINES= with SEND_APPLESCRIPT_FALLBACK=0 leaves the names server as the only",
        "    send engine, and it refuses every write. Without them, anything sent through the",
        "    demo relay is handed to Messages on this Mac. IMESSAGE_CLI=0 keeps the edit engine",
        "    out as well: where imessage-cli is installed the relay finds it by itself.",
        "  - IMSG_TOKEN was generated for this run: the demo relay may be reachable from the",
        "    network (the command leaves IMSG_BIND to .env; without that key the relay binds",
        "    every interface). Each build prints a new one. IMSG_PORT keeps the demo off an",
        "    installed relay's port (8700 unless changed).",
        "  - IMSG_STATE is the demo's own state file, apart from your real relay_state.json. It",
        "    records the push token of any phone that connects: keep it private.",
        "  - APPLE_NEWS_PREVIEWS=0 stops the relay from fetching the fictional apple.news link;",
        "    FEATURE_*=0 stops it from advertising FaceTime and voice.",
        "",
        "Before a screenshot, read the doctor table the relay prints at start. It must say:",
        "BlueBubbles \"password set, server reachable\" (the names server; \"unreachable\" means",
        "step 1 is not running and people show as numbers), Beeper \"disabled\", FCM push",
        "\"disabled\", Home Assistant \"disabled\", MapKit \"not set\", send engines \"bluebubbles\",",
        "features advertised \"(none)\".",
        "",
        "The demo is read-only: thread list, messages, replies, tapbacks, the edited message,",
        "the photo and the two link cards. Sending, tapbacks, new chats and FaceTime are refused",
        "with 501; they need the real setup, a Mac signed into Messages.",
        "",
        f"The phone cannot use http://<mac>:{relay_port}: the app speaks HTTPS only. Point an HTTPS",
        f"route at port {relay_port} for the session (README, \"Exposing the relay to the phone\"), then",
        "in the app: Settings, section Relay, that URL and the token above, Test connection,",
        "Save. Put the route and the app's own relay settings back afterwards.",
        "",
        "Times are fixed at build time: stop the demo relay, re-run this command and start the",
        "relay again right before taking screenshots. Re-running replaces the database (same",
        "--seed, --now, output path and time zone: same rows). Do not move the output folder;",
        "the photo is found by its recorded path. These files are local: do not commit or share",
        "them.",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="make_demo_db.py",
        description="Build a fictional chat.db for SelfBubbles screenshots and demos, "
                    "or serve its fictional contact names to a demo relay.")
    parser.add_argument("output", type=Path, nargs="?",
                        help="where to write the database: any path that is not under ~/Library "
                             "and not inside the relay checkout, e.g. ~/selfbubbles-demo/chat.db")
    parser.add_argument("--seed", type=int, default=1, help="jitter seed for timestamps and colours (default 1)")
    parser.add_argument("--now", default=None, metavar="ISO8601",
                        help="anchor the newest messages here instead of the current time "
                             "(e.g. 2026-10-06T18:00:00; the same seed, now, output path and "
                             "time zone give the same rows)")
    parser.add_argument("--relay-port", type=int, default=DEMO_RELAY_PORT, metavar="N",
                        help=f"the demo relay's port in the printed recipe (default {DEMO_RELAY_PORT})")
    parser.add_argument("--contacts-port", type=int, default=DEMO_CONTACTS_PORT, metavar="N",
                        help="the names server's port in the printed recipe "
                             f"(default {DEMO_CONTACTS_PORT})")
    parser.add_argument("--serve-contacts", nargs="?", type=int, const=DEMO_CONTACTS_PORT,
                        default=None, metavar="PORT",
                        help="instead of building: serve the fictional names on 127.0.0.1:PORT "
                             f"(default {DEMO_CONTACTS_PORT}) for a demo relay, until Ctrl-C")
    args = parser.parse_args(argv)
    if args.serve_contacts is not None:
        if args.output is not None:
            parser.error("--serve-contacts runs on its own; build the database in a separate run")
        return serve_contacts(args.serve_contacts)
    if args.output is None:
        parser.error("give the path of the database to build, or --serve-contacts")
    try:
        info = build_demo_db(args.output, seed=args.seed, now=_parse_now(args.now))
    except (UnsafeOutputPath, NotADemoDatabase) as e:
        print(f"error: {e}", file=sys.stderr)
        return 2
    ports = (args.relay_port, args.contacts_port)
    print(run_instructions(info, relay_port=args.relay_port, contacts_port=args.contacts_port,
                           busy_ports=tuple(p for p in ports if port_in_use(p))))
    return 0


if __name__ == "__main__":
    sys.exit(main())
